# Generated by Django 6.0.8 on 2026-08-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(db_index=True, max_length=30, verbose_name='Número de Cédula / ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='General', max_length=250, verbose_name='Categoría / Módulo')),
                ('texto', models.TextField(verbose_name='Pregunta')),
                ('opcion_a', models.TextField(verbose_name='Opción A')),
                ('opcion_b', models.TextField(verbose_name='Opción B')),
                ('opcion_c', models.TextField(verbose_name='Opción C')),
                ('opcion_d', models.TextField(verbose_name='Opción D')),
                ('opcion_correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1, verbose_name='Opción Correcta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje Obtenido')),
                ('total_preguntas', models.IntegerField(default=7, verbose_name='Total Preguntas')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje (%)')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('respuestas_detalle', models.JSONField(default=dict, verbose_name='Detalle de Respuestas')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Finalización')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='cuestionario.participante', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Intento de Cuestionario',
                'verbose_name_plural': 'Intentos de Cuestionarios',
                'ordering': ['-fecha_completado'],
            },
        ),
    ]
